### THIS FILE WAS GENERATED BY BREEZE TO BE USED BY SHINY.
### DO NOT EDIT, unless you know exactly what you are doing.
### Clinical dashboard shiny package
### developed by John patrick Mpindi
### Institute: FIMM - University of Helsinki Finland
### $generated
### $updated

library(shiny)
library(XLConnect)
library(googleVis)
library(markdown)
library(DT)
library(leaflet)
library(shinydashboard)
library(bootstrap)
library(rCharts)
library(ggplot2)
library(RPMG)


#Load the data-path
#Set the path based on location.
directory_path <- getwd()

###
### DYNAMICALY GENERATED CONTENT FOLLOWING
###
$tag_global
