### THIS FILE WAS GENERATED BY BREEZE TO BE USED BY SHINY.
### DO NOT EDIT, unless you know exactly what you are doing.
### $title
### $generated
### $updated

$loaders

server <- function(input, output,session) {
  #Source all the server files needed for each tag.
  $sources
}

