### THIS FILE WAS GENERATED BY BREEZE TO BE USED BY SHINY.
### DO NOT EDIT, unless you know exactly what you are doing.
### $title
### $generated
### $updated

#Tittle of report
title_header = "$title"
#Dashboard Header will be common for all shiny tags.
DashboardHeader_notification <- $header

#Dashboard Header call
header <- dashboardHeader(title=title_header, DashboardHeader_notification)


#Sidebar Menu will be common for all shiny tags.
report_sidebarMenu <- sidebarMenu(
  $menu_items
  menuItem(hr()),
  menuItem("Noozle report", icon = icon("eye-open", lib = "glyphicon"),badgeLabel = "report", badgeColor = "yellow",href = "nozzle"),
  menuItem(sidebarSearchForm(textId = "searchText", buttonId = "searchButton",label = "Search history..."))
)

#Sidebar call
sidebar <- dashboardSidebar(report_sidebarMenu)

#Start of calls for separate tags
#Source them from script body of each attached tag
$sources

#call the shiny tags attached to the report
all_tab_content <- tabItems(
  $tag_vars
)
#All body parts are assembled here
#This will be standard no change
body <- dashboardBody(all_tab_content)

#Now constructing the UI
#This will be standard no change
ui <- dashboardPage(header, sidebar, body)
 
  

