#!/bin/bash
# Non language specific, non target specific, job bootstrap file
# Clem 06/05/2016
# compatible with :
# 	compute targets : sge, docker
# 	language 	: R (possibly others)
# Configuration variables, parsed and filled from Breeze
FAILED_FN=$failed_fn
INCOMPLETE_FN=$inc_run_fn
SUCCESS_FN=$success_fn
DONE_FN=$done_fn
IN=$file_name
OUT=$out_file_name
EXEC_PATH=$full_path
EXEC_CMD="$cmd"
RUN_LINE="$EXEC_PATH $EXEC_CMD ./$IN"
FAILED_TEXT="$failed_txt"
POKE_URL="$poke_url"
## END OF CONFIGURATION
# Generated by Breeze for user $user on $date (local server time)
echo 'Current dir is '`pwd`
# removing possibly existing files generated from a previous run
rm *~ $OUT $FAILED_FN $INCOMPLETE_FN $SUCCESS_FN $DONE_FN > /dev/null 2>&1
echo -n 'Running '$IN'...'
# Running the job
touch ./$INCOMPLETE_FN && `$RUN_LINE` && touch ./$SUCCESS_FN
echo ' done !'
# Removes incomplete run file flag
rm ./$INCOMPLETE_FN > /dev/null 2>&1
CMD=`tail -n1<./$OUT`
# check the last line of the Rout file for possible job internal failure
if [ "$CMD" = "$FAILED_TEXT" ] || [ ! -f "$DONE_FN" ]; 
then
	touch ./$FAILED_FN
	cat $OUT
	echo 'Failure !'
	#less $OUT
	wget -qO- $POKE_URL'failed' > /dev/null
	exit 120
else
	wget -qO- $POKE_URL'success' > /dev/null
	echo 'Success !'	
fi
# removes any possible temp file (we don't want them to be part of the resulting folder)
rm *~ > /dev/null 2>&1
exit 0
